name: Keep Alive

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase
        run: |
          curl https://lyjhbzyykubeuvenmbjc.supabase.co/rest/v1/ \
          -H "apikey: sb_publishable_0Bj0zi07uA0KE4zZ7HO_pg_LlATbEAN"
